name: 'rebase action'
description: 'tries to rebase a repository onto another'

inputs:
  token:
    description: github token (needed if you want to the token to be triggering workflows)
    required: false
  upstream:
    description: upstream git repository url (https)
    required: false
  upstream-branch:
    description: branch to rebase the default branch onto
    required: false
  dispatch-token:
    description: token required for dispatch
    required: false
  dispatch-target:
    description: repository managing your packages
    required: false

runs:
  using: "composite"
  steps:
    - name: checkout
      uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      with:
        token: ${{ inputs.token || github.token }}
        fetch-depth: 0
    - name: setup
      shell: bash
      run: |
        git config user.email "bot@manjaro.download"
        git config user.name "Repository Update Bot"
        git config pull.rebase true
        echo ${{ github.token }} | gh auth login --with-token
    - name: update upstream tracking branch
      if: ${{ inputs.upstream != '' && inputs.upstream != '__UPSTREAM__' }}
      shell: bash
      env:
        UPSTREAM_BRANCH: ${{ inputs.upstream-branch }}
      run: |
        DEFAULT_BRANCH=$(git branch --show-current)
        UPSTREAM_BRANCH=${UPSTREAM_BRANCH:-$DEFAULT_BRANCH}
        UPSTREAM_TRACKING=upstream_${UPSTREAM_BRANCH}

        git remote add upstream ${{ inputs.upstream }}
        git fetch upstream

        git checkout upstream_${UPSTREAM_BRANCH} 2>/dev/null || git checkout -b upstream_${UPSTREAM_BRANCH}
        
        echo "## checking out the upstream branch"
        git reset --hard upstream/${UPSTREAM_BRANCH}

        git push --force --set-upstream origin upstream_${UPSTREAM_BRANCH}
        gh pr create --fill || exit 0
    - name: dispatch
      uses: peter-evans/repository-dispatch@26b39ed245ab8f31526069329e112ab2fb224588 # v2
      with:
        token: ${{ inputs.dispatch-token || github.token }}
        repository: ${{ inputs.dispatch-target || github.repository }}
        event-type: rebase
